include:
  - project: "davils/templates/gitlab-ci"
    ref: "main"
    file: "kotlin-java.yaml"
  - project: "davils/templates/gitlab-ci"
    ref: "main"
    file: "writerside.yaml"

stages:
  - build
  - test
  - publish
  - writerside-build
  - writerside-test

variables:
  CINTEROP_ENABLED: "true"
  TESTS_ENABLED: "true"
  JDK_VERSION: "jdk8"
  WRITERSIDE_INSTANCE: "docs/m"
